//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineLU.POLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Node
    {
        public Node()
        {
            this.NodeGpu = new HashSet<NodeGpu>();
            this.ProjectNodeTime = new HashSet<ProjectNodeTime>();
            this.ProjectSubmit = new HashSet<ProjectSubmit>();
        }
    
        public int Id { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime LastComunnication { get; set; }
        public string MachineName { get; set; }
        public bool Activated { get; set; }
        public string HardwareKey { get; set; }
        public int UserId { get; set; }
        public int NodeCpu_Id { get; set; }
    
        public virtual NodeCpu NodeCpu { get; set; }
        public virtual ICollection<NodeGpu> NodeGpu { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<ProjectNodeTime> ProjectNodeTime { get; set; }
        public virtual ICollection<ProjectSubmit> ProjectSubmit { get; set; }
    }
}
