//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("OnlineLUModel", "FK_NodeNodeCpu", "NodeCpu", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(OnlineLU.POLibrary.NodeCpu), "Node", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(OnlineLU.POLibrary.Node), true)]
[assembly: EdmRelationshipAttribute("OnlineLUModel", "FK_NodeNodeGpu", "Node", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(OnlineLU.POLibrary.Node), "NodeGpu", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(OnlineLU.POLibrary.NodeGpu), true)]
[assembly: EdmRelationshipAttribute("OnlineLUModel", "FK_UserNode", "User", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(OnlineLU.POLibrary.User), "Node", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(OnlineLU.POLibrary.Node), true)]
[assembly: EdmRelationshipAttribute("OnlineLUModel", "FK_ProjectUser", "User", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(OnlineLU.POLibrary.User), "Project", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(OnlineLU.POLibrary.Project), true)]
[assembly: EdmRelationshipAttribute("OnlineLUModel", "FK_ProjectSubmitProjectNodeTime", "ProjectNodeTime", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(OnlineLU.POLibrary.ProjectNodeTime), "ProjectSubmit", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(OnlineLU.POLibrary.ProjectSubmit), true)]
[assembly: EdmRelationshipAttribute("OnlineLUModel", "NodeProjectNodeTime", "Node", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(OnlineLU.POLibrary.Node), "ProjectNodeTime", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(OnlineLU.POLibrary.ProjectNodeTime))]
[assembly: EdmRelationshipAttribute("OnlineLUModel", "ProjectProjectSubmit", "Project", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(OnlineLU.POLibrary.Project), "ProjectSubmit", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(OnlineLU.POLibrary.ProjectSubmit))]
[assembly: EdmRelationshipAttribute("OnlineLUModel", "ProjectSubmitNode", "Node", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(OnlineLU.POLibrary.Node), "ProjectSubmit", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(OnlineLU.POLibrary.ProjectSubmit))]

#endregion

namespace OnlineLU.POLibrary
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class OnlineLUEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new OnlineLUEntities object using the connection string found in the 'OnlineLUEntities' section of the application configuration file.
        /// </summary>
        public OnlineLUEntities() : base("name=OnlineLUEntities", "OnlineLUEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new OnlineLUEntities object.
        /// </summary>
        public OnlineLUEntities(string connectionString) : base(connectionString, "OnlineLUEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new OnlineLUEntities object.
        /// </summary>
        public OnlineLUEntities(EntityConnection connection) : base(connection, "OnlineLUEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Node> Node
        {
            get
            {
                if ((_Node == null))
                {
                    _Node = base.CreateObjectSet<Node>("Node");
                }
                return _Node;
            }
        }
        private ObjectSet<Node> _Node;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<NodeCpu> NodeCpu
        {
            get
            {
                if ((_NodeCpu == null))
                {
                    _NodeCpu = base.CreateObjectSet<NodeCpu>("NodeCpu");
                }
                return _NodeCpu;
            }
        }
        private ObjectSet<NodeCpu> _NodeCpu;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<NodeGpu> NodeGpu
        {
            get
            {
                if ((_NodeGpu == null))
                {
                    _NodeGpu = base.CreateObjectSet<NodeGpu>("NodeGpu");
                }
                return _NodeGpu;
            }
        }
        private ObjectSet<NodeGpu> _NodeGpu;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Project> Project
        {
            get
            {
                if ((_Project == null))
                {
                    _Project = base.CreateObjectSet<Project>("Project");
                }
                return _Project;
            }
        }
        private ObjectSet<Project> _Project;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ProjectNodeTime> ProjectNodeTime
        {
            get
            {
                if ((_ProjectNodeTime == null))
                {
                    _ProjectNodeTime = base.CreateObjectSet<ProjectNodeTime>("ProjectNodeTime");
                }
                return _ProjectNodeTime;
            }
        }
        private ObjectSet<ProjectNodeTime> _ProjectNodeTime;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ProjectSubmit> ProjectSubmit
        {
            get
            {
                if ((_ProjectSubmit == null))
                {
                    _ProjectSubmit = base.CreateObjectSet<ProjectSubmit>("ProjectSubmit");
                }
                return _ProjectSubmit;
            }
        }
        private ObjectSet<ProjectSubmit> _ProjectSubmit;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<User> User
        {
            get
            {
                if ((_User == null))
                {
                    _User = base.CreateObjectSet<User>("User");
                }
                return _User;
            }
        }
        private ObjectSet<User> _User;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Node EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToNode(Node node)
        {
            base.AddObject("Node", node);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the NodeCpu EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToNodeCpu(NodeCpu nodeCpu)
        {
            base.AddObject("NodeCpu", nodeCpu);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the NodeGpu EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToNodeGpu(NodeGpu nodeGpu)
        {
            base.AddObject("NodeGpu", nodeGpu);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Project EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProject(Project project)
        {
            base.AddObject("Project", project);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ProjectNodeTime EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProjectNodeTime(ProjectNodeTime projectNodeTime)
        {
            base.AddObject("ProjectNodeTime", projectNodeTime);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ProjectSubmit EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProjectSubmit(ProjectSubmit projectSubmit)
        {
            base.AddObject("ProjectSubmit", projectSubmit);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the User EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUser(User user)
        {
            base.AddObject("User", user);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="OnlineLUModel", Name="Node")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Node : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Node object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="created">Initial value of the Created property.</param>
        /// <param name="lastComunnication">Initial value of the LastComunnication property.</param>
        /// <param name="machineName">Initial value of the MachineName property.</param>
        /// <param name="activated">Initial value of the Activated property.</param>
        /// <param name="userId">Initial value of the UserId property.</param>
        /// <param name="nodeCpu_Id">Initial value of the NodeCpu_Id property.</param>
        public static Node CreateNode(global::System.Int32 id, global::System.DateTime created, global::System.DateTime lastComunnication, global::System.String machineName, global::System.Boolean activated, global::System.Int32 userId, global::System.Int32 nodeCpu_Id)
        {
            Node node = new Node();
            node.Id = id;
            node.Created = created;
            node.LastComunnication = lastComunnication;
            node.MachineName = machineName;
            node.Activated = activated;
            node.UserId = userId;
            node.NodeCpu_Id = nodeCpu_Id;
            return node;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Created
        {
            get
            {
                return _Created;
            }
            set
            {
                OnCreatedChanging(value);
                ReportPropertyChanging("Created");
                _Created = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Created");
                OnCreatedChanged();
            }
        }
        private global::System.DateTime _Created;
        partial void OnCreatedChanging(global::System.DateTime value);
        partial void OnCreatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime LastComunnication
        {
            get
            {
                return _LastComunnication;
            }
            set
            {
                OnLastComunnicationChanging(value);
                ReportPropertyChanging("LastComunnication");
                _LastComunnication = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastComunnication");
                OnLastComunnicationChanged();
            }
        }
        private global::System.DateTime _LastComunnication;
        partial void OnLastComunnicationChanging(global::System.DateTime value);
        partial void OnLastComunnicationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MachineName
        {
            get
            {
                return _MachineName;
            }
            set
            {
                OnMachineNameChanging(value);
                ReportPropertyChanging("MachineName");
                _MachineName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MachineName");
                OnMachineNameChanged();
            }
        }
        private global::System.String _MachineName;
        partial void OnMachineNameChanging(global::System.String value);
        partial void OnMachineNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Activated
        {
            get
            {
                return _Activated;
            }
            set
            {
                OnActivatedChanging(value);
                ReportPropertyChanging("Activated");
                _Activated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Activated");
                OnActivatedChanged();
            }
        }
        private global::System.Boolean _Activated;
        partial void OnActivatedChanging(global::System.Boolean value);
        partial void OnActivatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String HardwareKey
        {
            get
            {
                return _HardwareKey;
            }
            set
            {
                OnHardwareKeyChanging(value);
                ReportPropertyChanging("HardwareKey");
                _HardwareKey = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("HardwareKey");
                OnHardwareKeyChanged();
            }
        }
        private global::System.String _HardwareKey;
        partial void OnHardwareKeyChanging(global::System.String value);
        partial void OnHardwareKeyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private global::System.Int32 _UserId;
        partial void OnUserIdChanging(global::System.Int32 value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 NodeCpu_Id
        {
            get
            {
                return _NodeCpu_Id;
            }
            set
            {
                OnNodeCpu_IdChanging(value);
                ReportPropertyChanging("NodeCpu_Id");
                _NodeCpu_Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NodeCpu_Id");
                OnNodeCpu_IdChanged();
            }
        }
        private global::System.Int32 _NodeCpu_Id;
        partial void OnNodeCpu_IdChanging(global::System.Int32 value);
        partial void OnNodeCpu_IdChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("OnlineLUModel", "FK_NodeNodeCpu", "NodeCpu")]
        public NodeCpu NodeCpu
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<NodeCpu>("OnlineLUModel.FK_NodeNodeCpu", "NodeCpu").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<NodeCpu>("OnlineLUModel.FK_NodeNodeCpu", "NodeCpu").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<NodeCpu> NodeCpuReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<NodeCpu>("OnlineLUModel.FK_NodeNodeCpu", "NodeCpu");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<NodeCpu>("OnlineLUModel.FK_NodeNodeCpu", "NodeCpu", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("OnlineLUModel", "FK_NodeNodeGpu", "NodeGpu")]
        public EntityCollection<NodeGpu> NodeGpu
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<NodeGpu>("OnlineLUModel.FK_NodeNodeGpu", "NodeGpu");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<NodeGpu>("OnlineLUModel.FK_NodeNodeGpu", "NodeGpu", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("OnlineLUModel", "FK_UserNode", "User")]
        public User User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("OnlineLUModel.FK_UserNode", "User").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("OnlineLUModel.FK_UserNode", "User").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("OnlineLUModel.FK_UserNode", "User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("OnlineLUModel.FK_UserNode", "User", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("OnlineLUModel", "NodeProjectNodeTime", "ProjectNodeTime")]
        public EntityCollection<ProjectNodeTime> ProjectNodeTime
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ProjectNodeTime>("OnlineLUModel.NodeProjectNodeTime", "ProjectNodeTime");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ProjectNodeTime>("OnlineLUModel.NodeProjectNodeTime", "ProjectNodeTime", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("OnlineLUModel", "ProjectSubmitNode", "ProjectSubmit")]
        public EntityCollection<ProjectSubmit> ProjectSubmit
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ProjectSubmit>("OnlineLUModel.ProjectSubmitNode", "ProjectSubmit");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ProjectSubmit>("OnlineLUModel.ProjectSubmitNode", "ProjectSubmit", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="OnlineLUModel", Name="NodeCpu")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class NodeCpu : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new NodeCpu object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="model">Initial value of the Model property.</param>
        /// <param name="processor">Initial value of the Processor property.</param>
        /// <param name="cores">Initial value of the Cores property.</param>
        /// <param name="memory">Initial value of the Memory property.</param>
        /// <param name="created">Initial value of the Created property.</param>
        public static NodeCpu CreateNodeCpu(global::System.Int32 id, global::System.String name, global::System.String model, global::System.String processor, global::System.String cores, global::System.Int32 memory, global::System.DateTime created)
        {
            NodeCpu nodeCpu = new NodeCpu();
            nodeCpu.Id = id;
            nodeCpu.Name = name;
            nodeCpu.Model = model;
            nodeCpu.Processor = processor;
            nodeCpu.Cores = cores;
            nodeCpu.Memory = memory;
            nodeCpu.Created = created;
            return nodeCpu;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Model
        {
            get
            {
                return _Model;
            }
            set
            {
                OnModelChanging(value);
                ReportPropertyChanging("Model");
                _Model = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Model");
                OnModelChanged();
            }
        }
        private global::System.String _Model;
        partial void OnModelChanging(global::System.String value);
        partial void OnModelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Processor
        {
            get
            {
                return _Processor;
            }
            set
            {
                OnProcessorChanging(value);
                ReportPropertyChanging("Processor");
                _Processor = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Processor");
                OnProcessorChanged();
            }
        }
        private global::System.String _Processor;
        partial void OnProcessorChanging(global::System.String value);
        partial void OnProcessorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Cores
        {
            get
            {
                return _Cores;
            }
            set
            {
                OnCoresChanging(value);
                ReportPropertyChanging("Cores");
                _Cores = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Cores");
                OnCoresChanged();
            }
        }
        private global::System.String _Cores;
        partial void OnCoresChanging(global::System.String value);
        partial void OnCoresChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Memory
        {
            get
            {
                return _Memory;
            }
            set
            {
                OnMemoryChanging(value);
                ReportPropertyChanging("Memory");
                _Memory = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Memory");
                OnMemoryChanged();
            }
        }
        private global::System.Int32 _Memory;
        partial void OnMemoryChanging(global::System.Int32 value);
        partial void OnMemoryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Created
        {
            get
            {
                return _Created;
            }
            set
            {
                OnCreatedChanging(value);
                ReportPropertyChanging("Created");
                _Created = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Created");
                OnCreatedChanged();
            }
        }
        private global::System.DateTime _Created;
        partial void OnCreatedChanging(global::System.DateTime value);
        partial void OnCreatedChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("OnlineLUModel", "FK_NodeNodeCpu", "Node")]
        public EntityCollection<Node> Node
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Node>("OnlineLUModel.FK_NodeNodeCpu", "Node");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Node>("OnlineLUModel.FK_NodeNodeCpu", "Node", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="OnlineLUModel", Name="NodeGpu")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class NodeGpu : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new NodeGpu object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="capability">Initial value of the Capability property.</param>
        /// <param name="cores">Initial value of the Cores property.</param>
        /// <param name="processor">Initial value of the Processor property.</param>
        /// <param name="memory">Initial value of the Memory property.</param>
        /// <param name="created">Initial value of the Created property.</param>
        /// <param name="node_Id">Initial value of the Node_Id property.</param>
        public static NodeGpu CreateNodeGpu(global::System.Int32 id, global::System.String name, global::System.String capability, global::System.Int32 cores, global::System.String processor, global::System.Int32 memory, global::System.DateTime created, global::System.Int32 node_Id)
        {
            NodeGpu nodeGpu = new NodeGpu();
            nodeGpu.Id = id;
            nodeGpu.Name = name;
            nodeGpu.Capability = capability;
            nodeGpu.Cores = cores;
            nodeGpu.Processor = processor;
            nodeGpu.Memory = memory;
            nodeGpu.Created = created;
            nodeGpu.Node_Id = node_Id;
            return nodeGpu;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Capability
        {
            get
            {
                return _Capability;
            }
            set
            {
                OnCapabilityChanging(value);
                ReportPropertyChanging("Capability");
                _Capability = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Capability");
                OnCapabilityChanged();
            }
        }
        private global::System.String _Capability;
        partial void OnCapabilityChanging(global::System.String value);
        partial void OnCapabilityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Cores
        {
            get
            {
                return _Cores;
            }
            set
            {
                OnCoresChanging(value);
                ReportPropertyChanging("Cores");
                _Cores = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Cores");
                OnCoresChanged();
            }
        }
        private global::System.Int32 _Cores;
        partial void OnCoresChanging(global::System.Int32 value);
        partial void OnCoresChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Processor
        {
            get
            {
                return _Processor;
            }
            set
            {
                OnProcessorChanging(value);
                ReportPropertyChanging("Processor");
                _Processor = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Processor");
                OnProcessorChanged();
            }
        }
        private global::System.String _Processor;
        partial void OnProcessorChanging(global::System.String value);
        partial void OnProcessorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Memory
        {
            get
            {
                return _Memory;
            }
            set
            {
                OnMemoryChanging(value);
                ReportPropertyChanging("Memory");
                _Memory = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Memory");
                OnMemoryChanged();
            }
        }
        private global::System.Int32 _Memory;
        partial void OnMemoryChanging(global::System.Int32 value);
        partial void OnMemoryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Created
        {
            get
            {
                return _Created;
            }
            set
            {
                OnCreatedChanging(value);
                ReportPropertyChanging("Created");
                _Created = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Created");
                OnCreatedChanged();
            }
        }
        private global::System.DateTime _Created;
        partial void OnCreatedChanging(global::System.DateTime value);
        partial void OnCreatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Node_Id
        {
            get
            {
                return _Node_Id;
            }
            set
            {
                OnNode_IdChanging(value);
                ReportPropertyChanging("Node_Id");
                _Node_Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Node_Id");
                OnNode_IdChanged();
            }
        }
        private global::System.Int32 _Node_Id;
        partial void OnNode_IdChanging(global::System.Int32 value);
        partial void OnNode_IdChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("OnlineLUModel", "FK_NodeNodeGpu", "Node")]
        public Node Node
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Node>("OnlineLUModel.FK_NodeNodeGpu", "Node").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Node>("OnlineLUModel.FK_NodeNodeGpu", "Node").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Node> NodeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Node>("OnlineLUModel.FK_NodeNodeGpu", "Node");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Node>("OnlineLUModel.FK_NodeNodeGpu", "Node", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="OnlineLUModel", Name="Project")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Project : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Project object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="created">Initial value of the Created property.</param>
        /// <param name="description">Initial value of the Description property.</param>
        /// <param name="user_Id">Initial value of the User_Id property.</param>
        public static Project CreateProject(global::System.Int32 id, global::System.DateTime created, global::System.String description, global::System.Int32 user_Id)
        {
            Project project = new Project();
            project.Id = id;
            project.Created = created;
            project.Description = description;
            project.User_Id = user_Id;
            return project;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Created
        {
            get
            {
                return _Created;
            }
            set
            {
                OnCreatedChanging(value);
                ReportPropertyChanging("Created");
                _Created = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Created");
                OnCreatedChanged();
            }
        }
        private global::System.DateTime _Created;
        partial void OnCreatedChanging(global::System.DateTime value);
        partial void OnCreatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 User_Id
        {
            get
            {
                return _User_Id;
            }
            set
            {
                OnUser_IdChanging(value);
                ReportPropertyChanging("User_Id");
                _User_Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("User_Id");
                OnUser_IdChanged();
            }
        }
        private global::System.Int32 _User_Id;
        partial void OnUser_IdChanging(global::System.Int32 value);
        partial void OnUser_IdChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("OnlineLUModel", "FK_ProjectUser", "User")]
        public User User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("OnlineLUModel.FK_ProjectUser", "User").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("OnlineLUModel.FK_ProjectUser", "User").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("OnlineLUModel.FK_ProjectUser", "User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("OnlineLUModel.FK_ProjectUser", "User", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("OnlineLUModel", "ProjectProjectSubmit", "ProjectSubmit")]
        public EntityCollection<ProjectSubmit> ProjectSubmit
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ProjectSubmit>("OnlineLUModel.ProjectProjectSubmit", "ProjectSubmit");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ProjectSubmit>("OnlineLUModel.ProjectProjectSubmit", "ProjectSubmit", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="OnlineLUModel", Name="ProjectNodeTime")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ProjectNodeTime : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ProjectNodeTime object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="nodeLocalProcess">Initial value of the NodeLocalProcess property.</param>
        public static ProjectNodeTime CreateProjectNodeTime(global::System.Int32 id, global::System.String nodeLocalProcess)
        {
            ProjectNodeTime projectNodeTime = new ProjectNodeTime();
            projectNodeTime.Id = id;
            projectNodeTime.NodeLocalProcess = nodeLocalProcess;
            return projectNodeTime;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTimeOffset> NodeQueueProcess
        {
            get
            {
                return _NodeQueueProcess;
            }
            set
            {
                OnNodeQueueProcessChanging(value);
                ReportPropertyChanging("NodeQueueProcess");
                _NodeQueueProcess = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NodeQueueProcess");
                OnNodeQueueProcessChanged();
            }
        }
        private Nullable<global::System.DateTimeOffset> _NodeQueueProcess;
        partial void OnNodeQueueProcessChanging(Nullable<global::System.DateTimeOffset> value);
        partial void OnNodeQueueProcessChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTimeOffset> NodeDownload
        {
            get
            {
                return _NodeDownload;
            }
            set
            {
                OnNodeDownloadChanging(value);
                ReportPropertyChanging("NodeDownload");
                _NodeDownload = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NodeDownload");
                OnNodeDownloadChanged();
            }
        }
        private Nullable<global::System.DateTimeOffset> _NodeDownload;
        partial void OnNodeDownloadChanging(Nullable<global::System.DateTimeOffset> value);
        partial void OnNodeDownloadChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTimeOffset> NodeThreadInstance
        {
            get
            {
                return _NodeThreadInstance;
            }
            set
            {
                OnNodeThreadInstanceChanging(value);
                ReportPropertyChanging("NodeThreadInstance");
                _NodeThreadInstance = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NodeThreadInstance");
                OnNodeThreadInstanceChanged();
            }
        }
        private Nullable<global::System.DateTimeOffset> _NodeThreadInstance;
        partial void OnNodeThreadInstanceChanging(Nullable<global::System.DateTimeOffset> value);
        partial void OnNodeThreadInstanceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTimeOffset> NodeUploadResult
        {
            get
            {
                return _NodeUploadResult;
            }
            set
            {
                OnNodeUploadResultChanging(value);
                ReportPropertyChanging("NodeUploadResult");
                _NodeUploadResult = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NodeUploadResult");
                OnNodeUploadResultChanged();
            }
        }
        private Nullable<global::System.DateTimeOffset> _NodeUploadResult;
        partial void OnNodeUploadResultChanging(Nullable<global::System.DateTimeOffset> value);
        partial void OnNodeUploadResultChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTimeOffset> NodePivot
        {
            get
            {
                return _NodePivot;
            }
            set
            {
                OnNodePivotChanging(value);
                ReportPropertyChanging("NodePivot");
                _NodePivot = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NodePivot");
                OnNodePivotChanged();
            }
        }
        private Nullable<global::System.DateTimeOffset> _NodePivot;
        partial void OnNodePivotChanging(Nullable<global::System.DateTimeOffset> value);
        partial void OnNodePivotChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NodeLocalProcess
        {
            get
            {
                return _NodeLocalProcess;
            }
            set
            {
                OnNodeLocalProcessChanging(value);
                ReportPropertyChanging("NodeLocalProcess");
                _NodeLocalProcess = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NodeLocalProcess");
                OnNodeLocalProcessChanged();
            }
        }
        private global::System.String _NodeLocalProcess;
        partial void OnNodeLocalProcessChanging(global::System.String value);
        partial void OnNodeLocalProcessChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("OnlineLUModel", "FK_ProjectSubmitProjectNodeTime", "ProjectSubmit")]
        public EntityCollection<ProjectSubmit> ProjectSubmit
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ProjectSubmit>("OnlineLUModel.FK_ProjectSubmitProjectNodeTime", "ProjectSubmit");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ProjectSubmit>("OnlineLUModel.FK_ProjectSubmitProjectNodeTime", "ProjectSubmit", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("OnlineLUModel", "NodeProjectNodeTime", "Node")]
        public EntityCollection<Node> Node
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Node>("OnlineLUModel.NodeProjectNodeTime", "Node");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Node>("OnlineLUModel.NodeProjectNodeTime", "Node", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="OnlineLUModel", Name="ProjectSubmit")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ProjectSubmit : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ProjectSubmit object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="submissionDate">Initial value of the SubmissionDate property.</param>
        /// <param name="endDate">Initial value of the EndDate property.</param>
        /// <param name="guid">Initial value of the Guid property.</param>
        /// <param name="projectNodeTime_Id">Initial value of the ProjectNodeTime_Id property.</param>
        public static ProjectSubmit CreateProjectSubmit(global::System.Int32 id, global::System.String submissionDate, global::System.String endDate, global::System.Guid guid, global::System.Int32 projectNodeTime_Id)
        {
            ProjectSubmit projectSubmit = new ProjectSubmit();
            projectSubmit.Id = id;
            projectSubmit.SubmissionDate = submissionDate;
            projectSubmit.EndDate = endDate;
            projectSubmit.Guid = guid;
            projectSubmit.ProjectNodeTime_Id = projectNodeTime_Id;
            return projectSubmit;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SubmissionDate
        {
            get
            {
                return _SubmissionDate;
            }
            set
            {
                OnSubmissionDateChanging(value);
                ReportPropertyChanging("SubmissionDate");
                _SubmissionDate = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SubmissionDate");
                OnSubmissionDateChanged();
            }
        }
        private global::System.String _SubmissionDate;
        partial void OnSubmissionDateChanging(global::System.String value);
        partial void OnSubmissionDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EndDate
        {
            get
            {
                return _EndDate;
            }
            set
            {
                OnEndDateChanging(value);
                ReportPropertyChanging("EndDate");
                _EndDate = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("EndDate");
                OnEndDateChanged();
            }
        }
        private global::System.String _EndDate;
        partial void OnEndDateChanging(global::System.String value);
        partial void OnEndDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Guid
        {
            get
            {
                return _Guid;
            }
            set
            {
                OnGuidChanging(value);
                ReportPropertyChanging("Guid");
                _Guid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Guid");
                OnGuidChanged();
            }
        }
        private global::System.Guid _Guid;
        partial void OnGuidChanging(global::System.Guid value);
        partial void OnGuidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ProjectNodeTime_Id
        {
            get
            {
                return _ProjectNodeTime_Id;
            }
            set
            {
                OnProjectNodeTime_IdChanging(value);
                ReportPropertyChanging("ProjectNodeTime_Id");
                _ProjectNodeTime_Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProjectNodeTime_Id");
                OnProjectNodeTime_IdChanged();
            }
        }
        private global::System.Int32 _ProjectNodeTime_Id;
        partial void OnProjectNodeTime_IdChanging(global::System.Int32 value);
        partial void OnProjectNodeTime_IdChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("OnlineLUModel", "FK_ProjectSubmitProjectNodeTime", "ProjectNodeTime")]
        public ProjectNodeTime ProjectNodeTime
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ProjectNodeTime>("OnlineLUModel.FK_ProjectSubmitProjectNodeTime", "ProjectNodeTime").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ProjectNodeTime>("OnlineLUModel.FK_ProjectSubmitProjectNodeTime", "ProjectNodeTime").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ProjectNodeTime> ProjectNodeTimeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ProjectNodeTime>("OnlineLUModel.FK_ProjectSubmitProjectNodeTime", "ProjectNodeTime");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ProjectNodeTime>("OnlineLUModel.FK_ProjectSubmitProjectNodeTime", "ProjectNodeTime", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("OnlineLUModel", "ProjectProjectSubmit", "Project")]
        public EntityCollection<Project> Project
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Project>("OnlineLUModel.ProjectProjectSubmit", "Project");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Project>("OnlineLUModel.ProjectProjectSubmit", "Project", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("OnlineLUModel", "ProjectSubmitNode", "Node")]
        public EntityCollection<Node> Node
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Node>("OnlineLUModel.ProjectSubmitNode", "Node");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Node>("OnlineLUModel.ProjectSubmitNode", "Node", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="OnlineLUModel", Name="User")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class User : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new User object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="created">Initial value of the Created property.</param>
        /// <param name="email">Initial value of the Email property.</param>
        /// <param name="password">Initial value of the Password property.</param>
        public static User CreateUser(global::System.Int32 id, global::System.DateTime created, global::System.String email, global::System.String password)
        {
            User user = new User();
            user.Id = id;
            user.Created = created;
            user.Email = email;
            user.Password = password;
            return user;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Created
        {
            get
            {
                return _Created;
            }
            set
            {
                OnCreatedChanging(value);
                ReportPropertyChanging("Created");
                _Created = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Created");
                OnCreatedChanged();
            }
        }
        private global::System.DateTime _Created;
        partial void OnCreatedChanging(global::System.DateTime value);
        partial void OnCreatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("OnlineLUModel", "FK_UserNode", "Node")]
        public EntityCollection<Node> Node
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Node>("OnlineLUModel.FK_UserNode", "Node");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Node>("OnlineLUModel.FK_UserNode", "Node", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("OnlineLUModel", "FK_ProjectUser", "Project")]
        public EntityCollection<Project> Project
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Project>("OnlineLUModel.FK_ProjectUser", "Project");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Project>("OnlineLUModel.FK_ProjectUser", "Project", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
