//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineLU.POLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Node = new HashSet<Node>();
            this.Project = new HashSet<Project>();
        }
    
        public int Id { get; set; }
        public System.DateTime Created { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
    
        public virtual ICollection<Node> Node { get; set; }
        public virtual ICollection<Project> Project { get; set; }
    }
}
