//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("OnlineLUModel", "FK_tbHardwaretbHistory", "tbHardware", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(OnlineLU.Server.POLibrary.tbHardware), "tbHistory", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(OnlineLU.Server.POLibrary.tbHistory), true)]
[assembly: EdmRelationshipAttribute("OnlineLUModel", "FK_tbHistorytbHistoryDetail", "tbHistoryDetail", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(OnlineLU.Server.POLibrary.tbHistoryDetail), "tbHistory", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(OnlineLU.Server.POLibrary.tbHistory), true)]
[assembly: EdmRelationshipAttribute("OnlineLUModel", "FK_tbProjects", "tbProject", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(OnlineLU.Server.POLibrary.tbProject), "tbHistory", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(OnlineLU.Server.POLibrary.tbHistory), true)]
[assembly: EdmRelationshipAttribute("OnlineLUModel", "FK_tbProjecttbUser", "tbUser", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(OnlineLU.Server.POLibrary.tbUser), "tbProject", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(OnlineLU.Server.POLibrary.tbProject), true)]

#endregion

namespace OnlineLU.Server.POLibrary
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class OnlineLUEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new OnlineLUEntities object using the connection string found in the 'OnlineLUEntities' section of the application configuration file.
        /// </summary>
        public OnlineLUEntities() : base("name=OnlineLUEntities", "OnlineLUEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new OnlineLUEntities object.
        /// </summary>
        public OnlineLUEntities(string connectionString) : base(connectionString, "OnlineLUEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new OnlineLUEntities object.
        /// </summary>
        public OnlineLUEntities(EntityConnection connection) : base(connection, "OnlineLUEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tbHardware> tbHardwares
        {
            get
            {
                if ((_tbHardwares == null))
                {
                    _tbHardwares = base.CreateObjectSet<tbHardware>("tbHardwares");
                }
                return _tbHardwares;
            }
        }
        private ObjectSet<tbHardware> _tbHardwares;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tbHistory> tbHistories
        {
            get
            {
                if ((_tbHistories == null))
                {
                    _tbHistories = base.CreateObjectSet<tbHistory>("tbHistories");
                }
                return _tbHistories;
            }
        }
        private ObjectSet<tbHistory> _tbHistories;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tbHistoryDetail> tbHistoryDetails
        {
            get
            {
                if ((_tbHistoryDetails == null))
                {
                    _tbHistoryDetails = base.CreateObjectSet<tbHistoryDetail>("tbHistoryDetails");
                }
                return _tbHistoryDetails;
            }
        }
        private ObjectSet<tbHistoryDetail> _tbHistoryDetails;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tbProject> tbProjects
        {
            get
            {
                if ((_tbProjects == null))
                {
                    _tbProjects = base.CreateObjectSet<tbProject>("tbProjects");
                }
                return _tbProjects;
            }
        }
        private ObjectSet<tbProject> _tbProjects;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tbUser> tbUsers
        {
            get
            {
                if ((_tbUsers == null))
                {
                    _tbUsers = base.CreateObjectSet<tbUser>("tbUsers");
                }
                return _tbUsers;
            }
        }
        private ObjectSet<tbUser> _tbUsers;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tbHardwares EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotbHardwares(tbHardware tbHardware)
        {
            base.AddObject("tbHardwares", tbHardware);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tbHistories EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotbHistories(tbHistory tbHistory)
        {
            base.AddObject("tbHistories", tbHistory);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tbHistoryDetails EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotbHistoryDetails(tbHistoryDetail tbHistoryDetail)
        {
            base.AddObject("tbHistoryDetails", tbHistoryDetail);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tbProjects EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotbProjects(tbProject tbProject)
        {
            base.AddObject("tbProjects", tbProject);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tbUsers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotbUsers(tbUser tbUser)
        {
            base.AddObject("tbUsers", tbUser);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="OnlineLUModel", Name="tbHardware")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbHardware : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tbHardware object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="hardwareKey">Initial value of the HardwareKey property.</param>
        public static tbHardware CreatetbHardware(global::System.Int64 id, global::System.String hardwareKey)
        {
            tbHardware tbHardware = new tbHardware();
            tbHardware.ID = id;
            tbHardware.HardwareKey = hardwareKey;
            return tbHardware;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String HardwareKey
        {
            get
            {
                return _HardwareKey;
            }
            set
            {
                OnHardwareKeyChanging(value);
                ReportPropertyChanging("HardwareKey");
                _HardwareKey = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("HardwareKey");
                OnHardwareKeyChanged();
            }
        }
        private global::System.String _HardwareKey;
        partial void OnHardwareKeyChanging(global::System.String value);
        partial void OnHardwareKeyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SystemName
        {
            get
            {
                return _SystemName;
            }
            set
            {
                OnSystemNameChanging(value);
                ReportPropertyChanging("SystemName");
                _SystemName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SystemName");
                OnSystemNameChanged();
            }
        }
        private global::System.String _SystemName;
        partial void OnSystemNameChanging(global::System.String value);
        partial void OnSystemNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CudaCapable
        {
            get
            {
                return _CudaCapable;
            }
            set
            {
                OnCudaCapableChanging(value);
                ReportPropertyChanging("CudaCapable");
                _CudaCapable = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CudaCapable");
                OnCudaCapableChanged();
            }
        }
        private global::System.String _CudaCapable;
        partial void OnCudaCapableChanging(global::System.String value);
        partial void OnCudaCapableChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CoreNumber
        {
            get
            {
                return _CoreNumber;
            }
            set
            {
                OnCoreNumberChanging(value);
                ReportPropertyChanging("CoreNumber");
                _CoreNumber = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CoreNumber");
                OnCoreNumberChanged();
            }
        }
        private Nullable<global::System.Int32> _CoreNumber;
        partial void OnCoreNumberChanging(Nullable<global::System.Int32> value);
        partial void OnCoreNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ProcessorName
        {
            get
            {
                return _ProcessorName;
            }
            set
            {
                OnProcessorNameChanging(value);
                ReportPropertyChanging("ProcessorName");
                _ProcessorName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ProcessorName");
                OnProcessorNameChanged();
            }
        }
        private global::System.String _ProcessorName;
        partial void OnProcessorNameChanging(global::System.String value);
        partial void OnProcessorNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> MemoryAmount
        {
            get
            {
                return _MemoryAmount;
            }
            set
            {
                OnMemoryAmountChanging(value);
                ReportPropertyChanging("MemoryAmount");
                _MemoryAmount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MemoryAmount");
                OnMemoryAmountChanged();
            }
        }
        private Nullable<global::System.Int32> _MemoryAmount;
        partial void OnMemoryAmountChanging(Nullable<global::System.Int32> value);
        partial void OnMemoryAmountChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("OnlineLUModel", "FK_tbHardwaretbHistory", "tbHistory")]
        public EntityCollection<tbHistory> tbHistories
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tbHistory>("OnlineLUModel.FK_tbHardwaretbHistory", "tbHistory");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tbHistory>("OnlineLUModel.FK_tbHardwaretbHistory", "tbHistory", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="OnlineLUModel", Name="tbHistory")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbHistory : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tbHistory object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="created">Initial value of the Created property.</param>
        /// <param name="modified">Initial value of the Modified property.</param>
        /// <param name="executionDate">Initial value of the ExecutionDate property.</param>
        /// <param name="success">Initial value of the Success property.</param>
        /// <param name="tbHistoryDetail_ID">Initial value of the tbHistoryDetail_ID property.</param>
        /// <param name="tbProjectID">Initial value of the tbProjectID property.</param>
        public static tbHistory CreatetbHistory(global::System.Int64 id, global::System.DateTime created, global::System.DateTime modified, global::System.DateTime executionDate, global::System.Boolean success, global::System.Int64 tbHistoryDetail_ID, global::System.Int64 tbProjectID)
        {
            tbHistory tbHistory = new tbHistory();
            tbHistory.ID = id;
            tbHistory.Created = created;
            tbHistory.Modified = modified;
            tbHistory.ExecutionDate = executionDate;
            tbHistory.Success = success;
            tbHistory.tbHistoryDetail_ID = tbHistoryDetail_ID;
            tbHistory.tbProjectID = tbProjectID;
            return tbHistory;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Created
        {
            get
            {
                return _Created;
            }
            set
            {
                OnCreatedChanging(value);
                ReportPropertyChanging("Created");
                _Created = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Created");
                OnCreatedChanged();
            }
        }
        private global::System.DateTime _Created;
        partial void OnCreatedChanging(global::System.DateTime value);
        partial void OnCreatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Modified
        {
            get
            {
                return _Modified;
            }
            set
            {
                OnModifiedChanging(value);
                ReportPropertyChanging("Modified");
                _Modified = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Modified");
                OnModifiedChanged();
            }
        }
        private global::System.DateTime _Modified;
        partial void OnModifiedChanging(global::System.DateTime value);
        partial void OnModifiedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime ExecutionDate
        {
            get
            {
                return _ExecutionDate;
            }
            set
            {
                OnExecutionDateChanging(value);
                ReportPropertyChanging("ExecutionDate");
                _ExecutionDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ExecutionDate");
                OnExecutionDateChanged();
            }
        }
        private global::System.DateTime _ExecutionDate;
        partial void OnExecutionDateChanging(global::System.DateTime value);
        partial void OnExecutionDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> TimeInitialUploadMs
        {
            get
            {
                return _TimeInitialUploadMs;
            }
            set
            {
                OnTimeInitialUploadMsChanging(value);
                ReportPropertyChanging("TimeInitialUploadMs");
                _TimeInitialUploadMs = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TimeInitialUploadMs");
                OnTimeInitialUploadMsChanged();
            }
        }
        private Nullable<global::System.Int64> _TimeInitialUploadMs;
        partial void OnTimeInitialUploadMsChanging(Nullable<global::System.Int64> value);
        partial void OnTimeInitialUploadMsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> TimeDownloadMs
        {
            get
            {
                return _TimeDownloadMs;
            }
            set
            {
                OnTimeDownloadMsChanging(value);
                ReportPropertyChanging("TimeDownloadMs");
                _TimeDownloadMs = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TimeDownloadMs");
                OnTimeDownloadMsChanged();
            }
        }
        private Nullable<global::System.Int64> _TimeDownloadMs;
        partial void OnTimeDownloadMsChanging(Nullable<global::System.Int64> value);
        partial void OnTimeDownloadMsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> TimeCudaMs
        {
            get
            {
                return _TimeCudaMs;
            }
            set
            {
                OnTimeCudaMsChanging(value);
                ReportPropertyChanging("TimeCudaMs");
                _TimeCudaMs = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TimeCudaMs");
                OnTimeCudaMsChanged();
            }
        }
        private Nullable<global::System.Int64> _TimeCudaMs;
        partial void OnTimeCudaMsChanging(Nullable<global::System.Int64> value);
        partial void OnTimeCudaMsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> TimeUploadMs
        {
            get
            {
                return _TimeUploadMs;
            }
            set
            {
                OnTimeUploadMsChanging(value);
                ReportPropertyChanging("TimeUploadMs");
                _TimeUploadMs = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TimeUploadMs");
                OnTimeUploadMsChanged();
            }
        }
        private Nullable<global::System.Int64> _TimeUploadMs;
        partial void OnTimeUploadMsChanging(Nullable<global::System.Int64> value);
        partial void OnTimeUploadMsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> TotalTimeMs
        {
            get
            {
                return _TotalTimeMs;
            }
            set
            {
                OnTotalTimeMsChanging(value);
                ReportPropertyChanging("TotalTimeMs");
                _TotalTimeMs = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TotalTimeMs");
                OnTotalTimeMsChanged();
            }
        }
        private Nullable<global::System.Int64> _TotalTimeMs;
        partial void OnTotalTimeMsChanging(Nullable<global::System.Int64> value);
        partial void OnTotalTimeMsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Success
        {
            get
            {
                return _Success;
            }
            set
            {
                OnSuccessChanging(value);
                ReportPropertyChanging("Success");
                _Success = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Success");
                OnSuccessChanged();
            }
        }
        private global::System.Boolean _Success;
        partial void OnSuccessChanging(global::System.Boolean value);
        partial void OnSuccessChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 tbHistoryDetail_ID
        {
            get
            {
                return _tbHistoryDetail_ID;
            }
            set
            {
                OntbHistoryDetail_IDChanging(value);
                ReportPropertyChanging("tbHistoryDetail_ID");
                _tbHistoryDetail_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("tbHistoryDetail_ID");
                OntbHistoryDetail_IDChanged();
            }
        }
        private global::System.Int64 _tbHistoryDetail_ID;
        partial void OntbHistoryDetail_IDChanging(global::System.Int64 value);
        partial void OntbHistoryDetail_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 tbProjectID
        {
            get
            {
                return _tbProjectID;
            }
            set
            {
                OntbProjectIDChanging(value);
                ReportPropertyChanging("tbProjectID");
                _tbProjectID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("tbProjectID");
                OntbProjectIDChanged();
            }
        }
        private global::System.Int64 _tbProjectID;
        partial void OntbProjectIDChanging(global::System.Int64 value);
        partial void OntbProjectIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> tbHardware_ID
        {
            get
            {
                return _tbHardware_ID;
            }
            set
            {
                OntbHardware_IDChanging(value);
                ReportPropertyChanging("tbHardware_ID");
                _tbHardware_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("tbHardware_ID");
                OntbHardware_IDChanged();
            }
        }
        private Nullable<global::System.Int64> _tbHardware_ID;
        partial void OntbHardware_IDChanging(Nullable<global::System.Int64> value);
        partial void OntbHardware_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Local
        {
            get
            {
                return _Local;
            }
            set
            {
                OnLocalChanging(value);
                ReportPropertyChanging("Local");
                _Local = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Local");
                OnLocalChanged();
            }
        }
        private global::System.String _Local;
        partial void OnLocalChanging(global::System.String value);
        partial void OnLocalChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("OnlineLUModel", "FK_tbHardwaretbHistory", "tbHardware")]
        public tbHardware tbHardware
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbHardware>("OnlineLUModel.FK_tbHardwaretbHistory", "tbHardware").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbHardware>("OnlineLUModel.FK_tbHardwaretbHistory", "tbHardware").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tbHardware> tbHardwareReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbHardware>("OnlineLUModel.FK_tbHardwaretbHistory", "tbHardware");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tbHardware>("OnlineLUModel.FK_tbHardwaretbHistory", "tbHardware", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("OnlineLUModel", "FK_tbHistorytbHistoryDetail", "tbHistoryDetail")]
        public tbHistoryDetail tbHistoryDetail
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbHistoryDetail>("OnlineLUModel.FK_tbHistorytbHistoryDetail", "tbHistoryDetail").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbHistoryDetail>("OnlineLUModel.FK_tbHistorytbHistoryDetail", "tbHistoryDetail").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tbHistoryDetail> tbHistoryDetailReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbHistoryDetail>("OnlineLUModel.FK_tbHistorytbHistoryDetail", "tbHistoryDetail");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tbHistoryDetail>("OnlineLUModel.FK_tbHistorytbHistoryDetail", "tbHistoryDetail", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("OnlineLUModel", "FK_tbProjects", "tbProject")]
        public tbProject tbProject
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbProject>("OnlineLUModel.FK_tbProjects", "tbProject").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbProject>("OnlineLUModel.FK_tbProjects", "tbProject").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tbProject> tbProjectReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbProject>("OnlineLUModel.FK_tbProjects", "tbProject");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tbProject>("OnlineLUModel.FK_tbProjects", "tbProject", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="OnlineLUModel", Name="tbHistoryDetail")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbHistoryDetail : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tbHistoryDetail object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static tbHistoryDetail CreatetbHistoryDetail(global::System.Int64 id)
        {
            tbHistoryDetail tbHistoryDetail = new tbHistoryDetail();
            tbHistoryDetail.ID = id;
            return tbHistoryDetail;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BytesDownload
        {
            get
            {
                return _BytesDownload;
            }
            set
            {
                OnBytesDownloadChanging(value);
                ReportPropertyChanging("BytesDownload");
                _BytesDownload = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BytesDownload");
                OnBytesDownloadChanged();
            }
        }
        private global::System.String _BytesDownload;
        partial void OnBytesDownloadChanging(global::System.String value);
        partial void OnBytesDownloadChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BytesUpload
        {
            get
            {
                return _BytesUpload;
            }
            set
            {
                OnBytesUploadChanging(value);
                ReportPropertyChanging("BytesUpload");
                _BytesUpload = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BytesUpload");
                OnBytesUploadChanged();
            }
        }
        private global::System.String _BytesUpload;
        partial void OnBytesUploadChanging(global::System.String value);
        partial void OnBytesUploadChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RateDownload
        {
            get
            {
                return _RateDownload;
            }
            set
            {
                OnRateDownloadChanging(value);
                ReportPropertyChanging("RateDownload");
                _RateDownload = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RateDownload");
                OnRateDownloadChanged();
            }
        }
        private global::System.String _RateDownload;
        partial void OnRateDownloadChanging(global::System.String value);
        partial void OnRateDownloadChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RateUpload
        {
            get
            {
                return _RateUpload;
            }
            set
            {
                OnRateUploadChanging(value);
                ReportPropertyChanging("RateUpload");
                _RateUpload = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RateUpload");
                OnRateUploadChanged();
            }
        }
        private global::System.String _RateUpload;
        partial void OnRateUploadChanging(global::System.String value);
        partial void OnRateUploadChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BytesInitialUpload
        {
            get
            {
                return _BytesInitialUpload;
            }
            set
            {
                OnBytesInitialUploadChanging(value);
                ReportPropertyChanging("BytesInitialUpload");
                _BytesInitialUpload = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BytesInitialUpload");
                OnBytesInitialUploadChanged();
            }
        }
        private global::System.String _BytesInitialUpload;
        partial void OnBytesInitialUploadChanging(global::System.String value);
        partial void OnBytesInitialUploadChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RateInitialUpload
        {
            get
            {
                return _RateInitialUpload;
            }
            set
            {
                OnRateInitialUploadChanging(value);
                ReportPropertyChanging("RateInitialUpload");
                _RateInitialUpload = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RateInitialUpload");
                OnRateInitialUploadChanged();
            }
        }
        private global::System.String _RateInitialUpload;
        partial void OnRateInitialUploadChanging(global::System.String value);
        partial void OnRateInitialUploadChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("OnlineLUModel", "FK_tbHistorytbHistoryDetail", "tbHistory")]
        public EntityCollection<tbHistory> tbHistories
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tbHistory>("OnlineLUModel.FK_tbHistorytbHistoryDetail", "tbHistory");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tbHistory>("OnlineLUModel.FK_tbHistorytbHistoryDetail", "tbHistory", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="OnlineLUModel", Name="tbProject")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbProject : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tbProject object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="created">Initial value of the Created property.</param>
        /// <param name="range">Initial value of the Range property.</param>
        /// <param name="containerName">Initial value of the ContainerName property.</param>
        /// <param name="containerNameResult">Initial value of the ContainerNameResult property.</param>
        /// <param name="queueName">Initial value of the QueueName property.</param>
        /// <param name="queueNameResult">Initial value of the QueueNameResult property.</param>
        /// <param name="tbUser_ID">Initial value of the tbUser_ID property.</param>
        public static tbProject CreatetbProject(global::System.Int64 id, global::System.DateTime created, global::System.Int32 range, global::System.String containerName, global::System.String containerNameResult, global::System.String queueName, global::System.String queueNameResult, global::System.Int64 tbUser_ID)
        {
            tbProject tbProject = new tbProject();
            tbProject.ID = id;
            tbProject.Created = created;
            tbProject.Range = range;
            tbProject.ContainerName = containerName;
            tbProject.ContainerNameResult = containerNameResult;
            tbProject.QueueName = queueName;
            tbProject.QueueNameResult = queueNameResult;
            tbProject.tbUser_ID = tbUser_ID;
            return tbProject;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Created
        {
            get
            {
                return _Created;
            }
            set
            {
                OnCreatedChanging(value);
                ReportPropertyChanging("Created");
                _Created = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Created");
                OnCreatedChanged();
            }
        }
        private global::System.DateTime _Created;
        partial void OnCreatedChanging(global::System.DateTime value);
        partial void OnCreatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Range
        {
            get
            {
                return _Range;
            }
            set
            {
                OnRangeChanging(value);
                ReportPropertyChanging("Range");
                _Range = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Range");
                OnRangeChanged();
            }
        }
        private global::System.Int32 _Range;
        partial void OnRangeChanging(global::System.Int32 value);
        partial void OnRangeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ContainerName
        {
            get
            {
                return _ContainerName;
            }
            set
            {
                OnContainerNameChanging(value);
                ReportPropertyChanging("ContainerName");
                _ContainerName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ContainerName");
                OnContainerNameChanged();
            }
        }
        private global::System.String _ContainerName;
        partial void OnContainerNameChanging(global::System.String value);
        partial void OnContainerNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ContainerNameResult
        {
            get
            {
                return _ContainerNameResult;
            }
            set
            {
                OnContainerNameResultChanging(value);
                ReportPropertyChanging("ContainerNameResult");
                _ContainerNameResult = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ContainerNameResult");
                OnContainerNameResultChanged();
            }
        }
        private global::System.String _ContainerNameResult;
        partial void OnContainerNameResultChanging(global::System.String value);
        partial void OnContainerNameResultChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String QueueName
        {
            get
            {
                return _QueueName;
            }
            set
            {
                OnQueueNameChanging(value);
                ReportPropertyChanging("QueueName");
                _QueueName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("QueueName");
                OnQueueNameChanged();
            }
        }
        private global::System.String _QueueName;
        partial void OnQueueNameChanging(global::System.String value);
        partial void OnQueueNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String QueueNameResult
        {
            get
            {
                return _QueueNameResult;
            }
            set
            {
                OnQueueNameResultChanging(value);
                ReportPropertyChanging("QueueNameResult");
                _QueueNameResult = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("QueueNameResult");
                OnQueueNameResultChanged();
            }
        }
        private global::System.String _QueueNameResult;
        partial void OnQueueNameResultChanging(global::System.String value);
        partial void OnQueueNameResultChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 tbUser_ID
        {
            get
            {
                return _tbUser_ID;
            }
            set
            {
                OntbUser_IDChanging(value);
                ReportPropertyChanging("tbUser_ID");
                _tbUser_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("tbUser_ID");
                OntbUser_IDChanged();
            }
        }
        private global::System.Int64 _tbUser_ID;
        partial void OntbUser_IDChanging(global::System.Int64 value);
        partial void OntbUser_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private Nullable<global::System.Boolean> _Status;
        partial void OnStatusChanging(Nullable<global::System.Boolean> value);
        partial void OnStatusChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("OnlineLUModel", "FK_tbProjects", "tbHistory")]
        public EntityCollection<tbHistory> tbHistories
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tbHistory>("OnlineLUModel.FK_tbProjects", "tbHistory");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tbHistory>("OnlineLUModel.FK_tbProjects", "tbHistory", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("OnlineLUModel", "FK_tbProjecttbUser", "tbUser")]
        public tbUser tbUser
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbUser>("OnlineLUModel.FK_tbProjecttbUser", "tbUser").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbUser>("OnlineLUModel.FK_tbProjecttbUser", "tbUser").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tbUser> tbUserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbUser>("OnlineLUModel.FK_tbProjecttbUser", "tbUser");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tbUser>("OnlineLUModel.FK_tbProjecttbUser", "tbUser", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="OnlineLUModel", Name="tbUser")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbUser : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tbUser object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="username">Initial value of the Username property.</param>
        /// <param name="password">Initial value of the Password property.</param>
        public static tbUser CreatetbUser(global::System.Int64 id, global::System.String username, global::System.String password)
        {
            tbUser tbUser = new tbUser();
            tbUser.ID = id;
            tbUser.Username = username;
            tbUser.Password = password;
            return tbUser;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Username
        {
            get
            {
                return _Username;
            }
            set
            {
                OnUsernameChanging(value);
                ReportPropertyChanging("Username");
                _Username = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Username");
                OnUsernameChanged();
            }
        }
        private global::System.String _Username;
        partial void OnUsernameChanging(global::System.String value);
        partial void OnUsernameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("OnlineLUModel", "FK_tbProjecttbUser", "tbProject")]
        public EntityCollection<tbProject> tbProjects
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tbProject>("OnlineLUModel.FK_tbProjecttbUser", "tbProject");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tbProject>("OnlineLUModel.FK_tbProjecttbUser", "tbProject", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
